const COMMON_DIRECT_TUNING = {
  directFocusLeadWeight: 0.08,
  directFocusLayerWeight: 0.04,
  directFocusAnchorWeight: 0.08,
  directFocusMax: 1.22,
  leadWetProtectLeadWeight: 0.12,
  leadWetProtectLayerWeight: 0.08,
  leadWetProtectAnchorWeight: 0.16,
  leadWetProtectMin: 0.62,
};

const COMMON_WET_TAIL_TUNING = {
  dynamicWetTrimDistanceScale: 0.52,
  dynamicWetTrimReverbScale: 0.26,
  dynamicWetTrimVolumeScale: 0.18,
  dynamicWetTrimLayerScale: 0.08,
  dynamicWetTrimMin: 0.56,
  wetMixReverbBase: 0.48,
  wetMixReverbScale: 92,
  wetMixLayerBase: 0.42,
  wetMixLayerScale: 0.78,
  earlyTailBase: 0.48,
  earlyTailWetTrimFloor: 0.72,
  earlyTailDistanceBase: 0.96,
  earlyTailDistanceScale: 0.16,
  earlyTailDistanceFloor: 0.58,
  lateTailBase: 0.58,
  lateTailDistanceBase: 0.72,
  lateTailDistanceScale: 0.16,
};

const COMMON_COMPRESSOR_TUNING = {
  compressorThresholdBase: -15,
  compressorThresholdSuppressionScale: 0.085,
  compressorThresholdLayerScale: 8.5,
  compressorKneeBase: 18,
  compressorKneeReverbScale: 0.17,
  compressorRatioBase: 1.8,
  compressorRatioSuppressionScale: 0.07,
  compressorRatioLayerScale: 4.6,
  compressorRatioMax: 18,
  compressorAttackBase: 0.017,
  compressorAttackSuppressionScale: 0.00008,
  compressorAttackLayerScale: 0.006,
  compressorAttackMin: 0.0015,
  compressorReleaseBase: 0.16,
  compressorReleaseLayerScale: 0.22,
  compressorReleaseSuppressionScale: 0.003,
  compressorReleaseReverbScale: 0.0015,
  compressorReleaseMax: 0.9,
};

const COMMON_TONE_TUNING = {
  airPresenceAbsorptionScale: 2.6,
  airPresenceExtraHighCutScale: 1.8,
  airPresenceArticulationScale: 2600,
  airPresenceLeadScale: 0.28,
  airBrillianceAbsorptionScale: 5.4,
  airBrillianceRoomEqScale: 1.8,
  airBrillianceExtraHighCutScale: 3.4,
  airBrillianceDirectCutScale: 1200,
  airBrillianceLeadScale: 0.18,
  presenceFrequencyBase: 2900,
  presenceArticulationScale: 0.24,
  presenceVariationScale: 0.34,
  presenceLayerScale: 0.42,
  presenceLeadScale: 0.55,
  transientFrequencyBase: 3400,
  transientLayerFrequencyScale: 560,
  transientVariationScale: 1,
  transientLayerScale: 0.28,
  transientLeadScale: 0.72,
};

const COMMON_AUX_TUNING = {
  diffusionDriveBase: 0.42,
  diffusionDriveReverbScale: 110,
  diffusionDistanceBase: 0.62,
  diffusionDistanceScale: 0.42,
  diffusionWetTrimFloor: 0.7,
  diffusionGainCap: 0.28,
  diffusionCutDistanceScale: 420,
  diffusionCutLayerScale: 320,
  diffusionHighpassBaseHz: 170,
  diffusionHighpassDistanceScale: 85,
  diffusionHighpassDirectScale: 0.028,
  diffusionHighpassWetBoostScale: 0.6,
  diffusionPanBase: 0.22,
  diffusionPanDistanceScale: 0.12,
  smearDensityFloor: 0.03,
  smearDensityScale: 0.14,
  smearLayerBase: 0.78,
  smearLayerScale: 0.22,
  smearPreDelayLayerMs: 10,
  smearPreDelayDelayScale: 0.012,
  smearLowpassBaseHz: 6900,
  smearLowpassLayerScale: 900,
  smearHighpassBaseHz: 150,
  smearHighpassDistanceScale: 78,
  smearHighpassDirectScale: 0.024,
  smearPanBase: 0.32,
  smearPanDistanceScale: 0.08,
  blurDensityFloor: 0.03,
  blurDensityScale: 0.11,
  blurLayerBase: 0.82,
  blurLayerScale: 0.18,
  blurPreDelayLayerMs: 4.5,
  blurBandpassBaseHz: 2200,
  blurBandpassLayerScale: 360,
  blurLowpassBaseHz: 5600,
  blurLowpassDirectScale: 0.5,
  blurPanScale: 0.2,
};

function flattenAudiencePreset(config) {
  const {
    preset,
    label,
    trackProfile,
    directTuning = {},
    wetTailTuning = {},
    compressorTuning = {},
    toneTuning = {},
    auxTuning = {},
    spatialTuning = {},
    mixTuning = {},
  } = config;

  return {
    preset,
    label,
    trackProfile,
    ...directTuning,
    ...wetTailTuning,
    ...compressorTuning,
    ...toneTuning,
    ...auxTuning,
    ...spatialTuning,
    ...mixTuning,
  };
}

export const AUDIENCE_PRESET_GROUPS = {
  front: {
    preset: "front",
    label: "Front",
    trackProfile: {
      volumeScale: { base: 1.04, front: 0.12, rear: -0.04, min: null },
      reverbExtra: { front: -18 },
      suppressionExtra: { front: -14 },
      clarityBoost: { front: 0 },
      wetMixTrim: { front: -0.08 },
    },
    directTuning: {
      ...COMMON_DIRECT_TUNING,
    },
    wetTailTuning: {
      ...COMMON_WET_TAIL_TUNING,
      wetMix: 0.86,
      tailGainScale: 0.92,
      reflectionBoost: 0.9,
      dynamicWetTrimStrength: 0,
      reflectionDepthTrimStrength: 0.12,
    },
    compressorTuning: {
      ...COMMON_COMPRESSOR_TUNING,
    },
    toneTuning: {
      ...COMMON_TONE_TUNING,
      directCutHz: 0,
      wetLowpassCut: 0,
      wetHighpassBoostHz: 0,
      wetLowShelfCutDb: 0,
      articulationCutHz: 0,
      presenceDipDb: -1.5,
      layerFadeMs: 26,
      transientDipDb: -1.5,
    },
    auxTuning: {
      ...COMMON_AUX_TUNING,
      transientBlurTapMs: [4, 9],
      transientBlurGain: 0.03,
      smearTapMs: [6, 11, 17],
      smearGain: 0.045,
      smearCutHz: 0,
      diffusionMix: 0.08,
      diffusionFeedback: 0.26,
      diffusionTimesMs: [9, 14, 21],
      diffusionCutHz: 5400,
      diffusionStereo: 0.08,
    },
    spatialTuning: {
      distanceOffset: -0.14,
      stereoWidth: 0.96,
      extraHighCut: 0.02,
      preDelayMs: -6,
      delayScale: 0.92,
      reflectionSpacing: 0.9,
      preDelayScale: 0.88,
    },
    mixTuning: {
      dryGain: 1.05,
      directMixTrim: 1,
    },
  },
  mid: {
    preset: "mid",
    label: "Middle",
    trackProfile: {
      volumeScale: { base: 0.92, front: 0.08, rear: -0.04, min: 0.8 },
      reverbExtra: { front: 10 },
      suppressionExtra: { front: 8 },
      clarityBoost: { front: 0.75 },
      wetMixTrim: { front: -0.12 },
    },
    directTuning: {
      ...COMMON_DIRECT_TUNING,
    },
    wetTailTuning: {
      ...COMMON_WET_TAIL_TUNING,
      wetMix: 1.08,
      tailGainScale: 1,
      reflectionBoost: 1.02,
      dynamicWetTrimStrength: 0,
      reflectionDepthTrimStrength: 0.18,
    },
    compressorTuning: {
      ...COMMON_COMPRESSOR_TUNING,
    },
    toneTuning: {
      ...COMMON_TONE_TUNING,
      directCutHz: 0,
      wetLowpassCut: 0,
      wetHighpassBoostHz: 0,
      wetLowShelfCutDb: 0,
      articulationCutHz: 240,
      presenceDipDb: -2.4,
      layerFadeMs: 42,
      transientDipDb: -4.5,
    },
    auxTuning: {
      ...COMMON_AUX_TUNING,
      transientBlurTapMs: [4, 7, 11, 17],
      transientBlurGain: 0.07,
      smearTapMs: [8, 15, 24, 35, 49],
      smearGain: 0.055,
      smearCutHz: 500,
      diffusionMix: 0.16,
      diffusionFeedback: 0.38,
      diffusionTimesMs: [10, 16, 24, 37],
      diffusionCutHz: 4200,
      diffusionStereo: 0.12,
    },
    spatialTuning: {
      distanceOffset: 0.04,
      stereoWidth: 1.02,
      extraHighCut: 0.14,
      preDelayMs: 4,
      delayScale: 1,
      reflectionSpacing: 1,
      preDelayScale: 1,
    },
    mixTuning: {
      dryGain: 1.06,
      directMixTrim: 0.97,
    },
  },
  rear: {
    preset: "rear",
    label: "Rear",
    trackProfile: {
      volumeScale: { base: 0.74, front: 0.12, rear: -0.02, min: 0.7 },
      reverbExtra: { front: 34 },
      suppressionExtra: { front: 30 },
      clarityBoost: { front: 1.1 },
      wetMixTrim: { front: -0.18 },
    },
    directTuning: {
      ...COMMON_DIRECT_TUNING,
    },
    wetTailTuning: {
      ...COMMON_WET_TAIL_TUNING,
      wetMix: 1.36,
      tailGainScale: 1.06,
      reflectionBoost: 1.06,
      dynamicWetTrimStrength: 0.22,
      reflectionDepthTrimStrength: 0.32,
    },
    compressorTuning: {
      ...COMMON_COMPRESSOR_TUNING,
    },
    toneTuning: {
      ...COMMON_TONE_TUNING,
      directCutHz: 700,
      wetLowpassCut: 240,
      wetHighpassBoostHz: 70,
      wetLowShelfCutDb: -3.5,
      articulationCutHz: 900,
      presenceDipDb: -4.5,
      layerFadeMs: 72,
      transientDipDb: -9,
    },
    auxTuning: {
      ...COMMON_AUX_TUNING,
      transientBlurTapMs: [4, 8, 13, 19, 28, 40],
      transientBlurGain: 0.07,
      smearTapMs: [10, 18, 29, 43, 60, 82],
      smearGain: 0.025,
      smearCutHz: 1200,
      diffusionMix: 0.21,
      diffusionFeedback: 0.26,
      diffusionTimesMs: [13, 21, 33, 49],
      diffusionCutHz: 3000,
      diffusionStereo: 0.12,
    },
    spatialTuning: {
      distanceOffset: 0.2,
      stereoWidth: 1.1,
      extraHighCut: 0.32,
      preDelayMs: 12,
      delayScale: 1.12,
      reflectionSpacing: 1.22,
      preDelayScale: 1.24,
    },
    mixTuning: {
      dryGain: 1.12,
      directMixTrim: 0.94,
    },
  },
  outside: {
    preset: "outside",
    label: "Outside",
    trackProfile: {
      volumeScale: { base: 0.2, front: 0, rear: -0.01, min: 0.16 },
      reverbExtra: { front: 34 },
      suppressionExtra: { front: 58 },
      clarityBoost: { front: 0.18 },
      wetMixTrim: { front: -0.03 },
    },
    directTuning: {
      directFocusLeadWeight: 0.05,
      directFocusLayerWeight: 0.02,
      directFocusAnchorWeight: 0.04,
      directFocusMax: 1.1,
      leadWetProtectLeadWeight: 0.08,
      leadWetProtectLayerWeight: 0.04,
      leadWetProtectAnchorWeight: 0.1,
      leadWetProtectMin: 0.72,
    },
    wetTailTuning: {
      dynamicWetTrimDistanceScale: 0.6,
      dynamicWetTrimReverbScale: 0.3,
      dynamicWetTrimVolumeScale: 0.22,
      dynamicWetTrimLayerScale: 0.12,
      dynamicWetTrimMin: 0.62,
      wetMixReverbBase: 0.54,
      wetMixReverbScale: 82,
      wetMixLayerBase: 0.36,
      wetMixLayerScale: 0.66,
      earlyTailBase: 0.52,
      earlyTailWetTrimFloor: 0.78,
      earlyTailDistanceBase: 0.94,
      earlyTailDistanceScale: 0.16,
      earlyTailDistanceFloor: 0.6,
      lateTailBase: 0.56,
      lateTailDistanceBase: 0.76,
      lateTailDistanceScale: 0.18,
      wetMix: 1.66,
      tailGainScale: 1.12,
      reflectionBoost: 0.88,
      dynamicWetTrimStrength: 0.3,
      reflectionDepthTrimStrength: 0.36,
    },
    compressorTuning: {
      compressorThresholdBase: -13.5,
      compressorThresholdSuppressionScale: 0.074,
      compressorThresholdLayerScale: 7.2,
      compressorKneeBase: 20,
      compressorKneeReverbScale: 0.14,
      compressorRatioBase: 1.5,
      compressorRatioSuppressionScale: 0.055,
      compressorRatioLayerScale: 3.7,
      compressorRatioMax: 14,
      compressorAttackBase: 0.019,
      compressorAttackSuppressionScale: 0.00006,
      compressorAttackLayerScale: 0.0048,
      compressorAttackMin: 0.0028,
      compressorReleaseBase: 0.2,
      compressorReleaseLayerScale: 0.18,
      compressorReleaseSuppressionScale: 0.0024,
      compressorReleaseReverbScale: 0.0012,
      compressorReleaseMax: 0.82,
    },
    toneTuning: {
      airPresenceAbsorptionScale: 3.1,
      airPresenceExtraHighCutScale: 2.2,
      airPresenceArticulationScale: 2100,
      airPresenceLeadScale: 0.18,
      airBrillianceAbsorptionScale: 6.3,
      airBrillianceRoomEqScale: 2.2,
      airBrillianceExtraHighCutScale: 4.1,
      airBrillianceDirectCutScale: 980,
      airBrillianceLeadScale: 0.1,
      presenceFrequencyBase: 2600,
      presenceArticulationScale: 0.3,
      presenceVariationScale: 0.26,
      presenceLayerScale: 0.32,
      presenceLeadScale: 0.32,
      transientFrequencyBase: 3000,
      transientLayerFrequencyScale: 420,
      transientVariationScale: 0.72,
      transientLayerScale: 0.18,
      transientLeadScale: 0.34,
      directCutHz: 2400,
      wetLowpassCut: 1100,
      wetHighpassBoostHz: 120,
      wetLowShelfCutDb: -4.8,
      articulationCutHz: 2600,
      presenceDipDb: -10.5,
      layerFadeMs: 120,
      transientDipDb: -16,
    },
    auxTuning: {
      ...COMMON_AUX_TUNING,
      transientBlurTapMs: [5, 9, 15, 22, 31, 44, 60],
      transientBlurGain: 0.1,
      smearTapMs: [18, 30, 47, 67, 90, 119, 153, 194],
      smearGain: 0.04,
      smearCutHz: 3000,
      diffusionMix: 0.26,
      diffusionFeedback: 0.3,
      diffusionTimesMs: [19, 32, 51, 79],
      diffusionCutHz: 2200,
      diffusionStereo: 0.18,
      diffusionDriveBase: 0.46,
      diffusionDriveReverbScale: 96,
      diffusionDistanceBase: 0.72,
      diffusionDistanceScale: 0.44,
      diffusionWetTrimFloor: 0.76,
      diffusionGainCap: 0.3,
      diffusionCutDistanceScale: 520,
      diffusionCutLayerScale: 380,
      diffusionHighpassBaseHz: 190,
      diffusionHighpassDistanceScale: 94,
      diffusionHighpassDirectScale: 0.03,
      diffusionHighpassWetBoostScale: 0.68,
      diffusionPanBase: 0.2,
      diffusionPanDistanceScale: 0.1,
      smearDensityFloor: 0.04,
      smearDensityScale: 0.16,
      smearLayerBase: 0.84,
      smearLayerScale: 0.28,
      smearPreDelayLayerMs: 10,
      smearPreDelayDelayScale: 0.015,
      smearLowpassBaseHz: 6700,
      smearLowpassLayerScale: 1040,
      smearHighpassBaseHz: 180,
      smearHighpassDistanceScale: 88,
      smearHighpassDirectScale: 0.026,
      smearPanBase: 0.28,
      smearPanDistanceScale: 0.06,
      blurDensityFloor: 0.04,
      blurDensityScale: 0.13,
      blurLayerBase: 0.86,
      blurLayerScale: 0.2,
      blurPreDelayLayerMs: 5.2,
      blurBandpassBaseHz: 2000,
      blurBandpassLayerScale: 300,
      blurLowpassBaseHz: 5400,
      blurLowpassDirectScale: 0.44,
      blurPanScale: 0.22,
    },
    spatialTuning: {
      distanceOffset: 0.34,
      stereoWidth: 1.16,
      extraHighCut: 0.66,
      preDelayMs: 24,
      delayScale: 1.24,
      reflectionSpacing: 1.34,
      preDelayScale: 1.34,
    },
    mixTuning: {
      dryGain: 0.82,
      directMixTrim: 0.82,
    },
  },
};

export const AUDIENCE_PRESETS = Object.fromEntries(
  Object.entries(AUDIENCE_PRESET_GROUPS).map(([key, value]) => [key, flattenAudiencePreset(value)]),
);
