export const ROOM_PRESETS = {
  dry: {
    label: "Dry",
    wetMix: 0.015,
    earlyWetMix: 0.82,
    lateWetMix: 0.22,
    earlyReverbSeconds: 0.08,
    lateReverbSeconds: 0.32,
    earlyDecayPower: 2.6,
    lateDecayPower: 3.2,
    earlyPreDelayMs: 1,
    latePreDelayMs: 4,
    reverbSeconds: 0.55,
    decayPower: 3.2,
    preDelayMs: 4,
    earlyReflections: [
      { timeMs: 9, pan: -0.16, gainDb: -1.2, filterHz: 7200 },
      { timeMs: 17, pan: 0.12, gainDb: -2.4, filterHz: 6000 },
    ],
    stereoWidth: 0.03,
    reflectionWidth: 0.1,
    distanceEq: 0.12,
    earlyToneCut: 0,
    lateToneCut: 120,
    wetToneCut: 0,
    directToneLift: 1.4,
  },
  stage: {
    label: "Stage",
    wetMix: 0.075,
    earlyWetMix: 0.68,
    lateWetMix: 0.42,
    earlyReverbSeconds: 0.16,
    lateReverbSeconds: 1.05,
    earlyDecayPower: 2.2,
    lateDecayPower: 2.35,
    earlyPreDelayMs: 4,
    latePreDelayMs: 10,
    reverbSeconds: 1.25,
    decayPower: 2.35,
    preDelayMs: 10,
    earlyReflections: [
      { timeMs: 10, pan: -0.26, gainDb: -1.2, filterHz: 7600 },
      { timeMs: 18, pan: 0.2, gainDb: -2.2, filterHz: 6500 },
      { timeMs: 27, pan: -0.08, gainDb: -3.4, filterHz: 5600 },
    ],
    stereoWidth: 0.09,
    reflectionWidth: 0.2,
    distanceEq: 0.28,
    earlyToneCut: 80,
    lateToneCut: 240,
    wetToneCut: 180,
    directToneLift: 0.6,
  },
  hall: {
    label: "Hall",
    wetMix: 0.24,
    earlyWetMix: 0.54,
    lateWetMix: 0.78,
    earlyReverbSeconds: 0.24,
    lateReverbSeconds: 3.6,
    earlyDecayPower: 1.95,
    lateDecayPower: 1.65,
    earlyPreDelayMs: 10,
    latePreDelayMs: 28,
    reverbSeconds: 3.6,
    decayPower: 1.65,
    preDelayMs: 28,
    earlyReflections: [
      { timeMs: 14, pan: -0.34, gainDb: -1.4, filterHz: 8200 },
      { timeMs: 29, pan: 0.28, gainDb: -2.1, filterHz: 6900 },
      { timeMs: 46, pan: -0.1, gainDb: -3.2, filterHz: 5600 },
      { timeMs: 66, pan: 0.12, gainDb: -4.4, filterHz: 4600 },
    ],
    stereoWidth: 0.2,
    reflectionWidth: 0.4,
    distanceEq: 0.62,
    earlyToneCut: 220,
    lateToneCut: 680,
    wetToneCut: 540,
    directToneLift: -0.6,
  },
  cathedral: {
    label: "Cathedral",
    wetMix: 0.38,
    earlyWetMix: 0.42,
    lateWetMix: 0.98,
    earlyReverbSeconds: 0.34,
    lateReverbSeconds: 6.4,
    earlyDecayPower: 1.72,
    lateDecayPower: 1.18,
    earlyPreDelayMs: 16,
    latePreDelayMs: 42,
    reverbSeconds: 6.4,
    decayPower: 1.18,
    preDelayMs: 42,
    earlyReflections: [
      { timeMs: 21, pan: -0.42, gainDb: -1.6, filterHz: 7800 },
      { timeMs: 39, pan: 0.36, gainDb: -2.4, filterHz: 6500 },
      { timeMs: 58, pan: -0.18, gainDb: -3.4, filterHz: 5400 },
      { timeMs: 79, pan: 0.14, gainDb: -4.4, filterHz: 4500 },
      { timeMs: 104, pan: -0.08, gainDb: -5.6, filterHz: 3900 },
      { timeMs: 132, pan: 0.06, gainDb: -6.6, filterHz: 3400 },
    ],
    stereoWidth: 0.3,
    reflectionWidth: 0.56,
    distanceEq: 0.9,
    earlyToneCut: 420,
    lateToneCut: 1260,
    wetToneCut: 1100,
    directToneLift: -1.8,
  },
};

export const AUDIENCE_PRESETS = {
  front: {
    preset: "front",
    label: "Front",
    distanceOffset: -0.14,
    dryGain: 1.05,
    directMixTrim: 1,
    wetMix: 0.86,
    stereoWidth: 0.96,
    reflectionBoost: 0.9,
    extraHighCut: 0.02,
    preDelayMs: -6,
    delayScale: 0.92,
    reflectionSpacing: 0.9,
    preDelayScale: 0.88,
    tailGainScale: 0.92,
    directCutHz: 0,
    wetLowpassCut: 0,
    wetHighpassBoostHz: 0,
    wetLowShelfCutDb: 0,
    dynamicWetTrimStrength: 0,
    reflectionDepthTrimStrength: 0.12,
    articulationCutHz: 0,
    presenceDipDb: -1.5,
    layerFadeMs: 26,
    transientDipDb: -1.5,
    transientBlurTapMs: [4, 9],
    transientBlurGain: 0.03,
    smearTapMs: [6, 11, 17],
    smearGain: 0.045,
    smearCutHz: 0,
    diffusionMix: 0.08,
    diffusionFeedback: 0.26,
    diffusionTimesMs: [9, 14, 21],
    diffusionCutHz: 5400,
    diffusionStereo: 0.08,
  },
  mid: {
    preset: "mid",
    label: "Middle",
    distanceOffset: 0.04,
    dryGain: 1.06,
    directMixTrim: 0.97,
    wetMix: 1.08,
    stereoWidth: 1.02,
    reflectionBoost: 1.02,
    extraHighCut: 0.14,
    preDelayMs: 4,
    delayScale: 1,
    reflectionSpacing: 1,
    preDelayScale: 1,
    tailGainScale: 1,
    directCutHz: 0,
    wetLowpassCut: 0,
    wetHighpassBoostHz: 0,
    wetLowShelfCutDb: 0,
    dynamicWetTrimStrength: 0,
    reflectionDepthTrimStrength: 0.18,
    articulationCutHz: 240,
    presenceDipDb: -2.4,
    layerFadeMs: 42,
    transientDipDb: -4.5,
    transientBlurTapMs: [4, 7, 11, 17],
    transientBlurGain: 0.07,
    smearTapMs: [8, 15, 24, 35, 49],
    smearGain: 0.055,
    smearCutHz: 500,
    diffusionMix: 0.16,
    diffusionFeedback: 0.38,
    diffusionTimesMs: [10, 16, 24, 37],
    diffusionCutHz: 4200,
    diffusionStereo: 0.12,
  },
  rear: {
    preset: "rear",
    label: "Rear",
    distanceOffset: 0.2,
    dryGain: 1.12,
    directMixTrim: 0.94,
    wetMix: 1.36,
    stereoWidth: 1.1,
    reflectionBoost: 1.06,
    extraHighCut: 0.32,
    preDelayMs: 12,
    delayScale: 1.12,
    reflectionSpacing: 1.22,
    preDelayScale: 1.24,
    tailGainScale: 1.06,
    directCutHz: 700,
    wetLowpassCut: 240,
    wetHighpassBoostHz: 70,
    wetLowShelfCutDb: -3.5,
    dynamicWetTrimStrength: 0.22,
    reflectionDepthTrimStrength: 0.32,
    articulationCutHz: 900,
    presenceDipDb: -4.5,
    layerFadeMs: 72,
    transientDipDb: -9,
    transientBlurTapMs: [4, 8, 13, 19, 28, 40],
    transientBlurGain: 0.07,
    smearTapMs: [10, 18, 29, 43, 60, 82],
    smearGain: 0.025,
    smearCutHz: 1200,
    diffusionMix: 0.21,
    diffusionFeedback: 0.26,
    diffusionTimesMs: [13, 21, 33, 49],
    diffusionCutHz: 3000,
    diffusionStereo: 0.12,
  },
  outside: {
    preset: "outside",
    label: "Outside",
    distanceOffset: 0.34,
    dryGain: 0.86,
    directMixTrim: 0.86,
    wetMix: 1.62,
    stereoWidth: 1.16,
    reflectionBoost: 1.12,
    extraHighCut: 0.64,
    preDelayMs: 26,
    delayScale: 1.24,
    reflectionSpacing: 1.48,
    preDelayScale: 1.42,
    tailGainScale: 1.12,
    directCutHz: 2200,
    wetLowpassCut: 1100,
    wetHighpassBoostHz: 120,
    wetLowShelfCutDb: -5.5,
    dynamicWetTrimStrength: 0.34,
    reflectionDepthTrimStrength: 0.42,
    articulationCutHz: 2400,
    presenceDipDb: -9,
    layerFadeMs: 120,
    transientDipDb: -14,
    transientBlurTapMs: [4, 8, 13, 19, 27, 38, 52],
    transientBlurGain: 0.08,
    smearTapMs: [14, 23, 37, 52, 69, 91, 118, 152],
    smearGain: 0.03,
    smearCutHz: 2400,
    diffusionMix: 0.27,
    diffusionFeedback: 0.3,
    diffusionTimesMs: [15, 25, 39, 61],
    diffusionCutHz: 2400,
    diffusionStereo: 0.14,
  },
};

export const AUDIENCE_TRACK_PROFILE_FACTORS = {
  front: {
    volumeScale: { base: 1.04, front: 0.12, rear: -0.04, min: null },
    reverbExtra: { front: -18 },
    suppressionExtra: { front: -14 },
    clarityBoost: { front: 0 },
    wetMixTrim: { front: -0.08 },
  },
  mid: {
    volumeScale: { base: 0.92, front: 0.08, rear: -0.04, min: 0.8 },
    reverbExtra: { front: 10 },
    suppressionExtra: { front: 8 },
    clarityBoost: { front: 0.75 },
    wetMixTrim: { front: -0.12 },
  },
  rear: {
    volumeScale: { base: 0.74, front: 0.12, rear: -0.02, min: 0.7 },
    reverbExtra: { front: 34 },
    suppressionExtra: { front: 30 },
    clarityBoost: { front: 1.1 },
    wetMixTrim: { front: -0.18 },
  },
  outside: {
    volumeScale: { base: 0.17, front: 0.05, rear: -0.01, min: 0.14 },
    reverbExtra: { front: 48 },
    suppressionExtra: { front: 42 },
    clarityBoost: { front: 1.4 },
    wetMixTrim: { front: -0.24 },
  },
};

export const DEFAULT_SETTINGS = {
  enabled: true,
  roomPreset: "hall",
  audiencePreset: "mid",
  cloneCount: 3,
  directMixTrim: 100,
  preDelayScale: 100,
  tailGainScale: 100,
  reflectionSpacing: 100,
  dynamicWetTrimStrength: 100,
  ensembleVolume: 70,
  volumeDecay: 50,
  delayMs: 160,
  reverbIntensity: 40,
  diffusionAmount: 90,
  auxiliaryAmount: 90,
  peakSuppression: 62,
  width: 55,
  tone: 0,
  outputGain: 78,
  originalMix: 18,
};

export function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

export function normalizeEarlyReflectionSet(entries, fallbackWidth = 0.2) {
  const sourceEntries = Array.isArray(entries) && entries.length ? entries : [8, 15, 24];
  return sourceEntries.map((entry, index) => {
    if (entry && typeof entry === "object" && !Array.isArray(entry)) {
      return {
        timeMs: Math.max(0, Number(entry.timeMs) || 0),
        pan: Math.max(-1, Math.min(1, Number(entry.pan) || 0)),
        gainDb: Number(entry.gainDb) || 0,
        filterHz: Math.max(800, Number(entry.filterHz) || 5200),
      };
    }
    const timeMs = Math.max(0, Number(entry) || 0);
    const direction = index % 2 === 0 ? -1 : 1;
    return {
      timeMs,
      pan: Math.max(-1, Math.min(1, direction * fallbackWidth * (0.65 + index * 0.12))),
      gainDb: -index * 1.2,
      filterHz: Math.max(1400, 8200 - index * 900),
    };
  });
}

export function getRoomPresetConfig(presetName) {
  const preset = ROOM_PRESETS[presetName] || ROOM_PRESETS.hall;
  const earlyReflections = normalizeEarlyReflectionSet(preset.earlyReflections, preset.reflectionWidth);
  return { ...preset, earlyReflections, earlyReflectionsMs: earlyReflections.map((entry) => entry.timeMs) };
}

export function getAudiencePresetConfig(presetName) {
  return AUDIENCE_PRESETS[presetName] || AUDIENCE_PRESETS.mid;
}

export function getAudienceTrackProfile(presetName, layerIndex, trackCount) {
  const factors = AUDIENCE_TRACK_PROFILE_FACTORS[presetName] || AUDIENCE_TRACK_PROFILE_FACTORS.mid;
  const totalTracks = Math.max(1, trackCount || 1);
  const frontWeight = totalTracks <= 1 ? 1 : Math.max(0, 1 - (layerIndex / (totalTracks - 1)) * 0.85);
  const rearWeight = totalTracks <= 1 ? 0 : layerIndex / (totalTracks - 1);
  const volumeScaleRaw = factors.volumeScale.base + frontWeight * factors.volumeScale.front + rearWeight * factors.volumeScale.rear;
  return {
    volumeScale: factors.volumeScale.min === null ? volumeScaleRaw : Math.max(factors.volumeScale.min, volumeScaleRaw),
    reverbExtra: (factors.reverbExtra.front || 0) * frontWeight,
    suppressionExtra: (factors.suppressionExtra.front || 0) * frontWeight,
    clarityBoost: (factors.clarityBoost.front || 0) * frontWeight,
    wetMixTrim: (factors.wetMixTrim.front || 0) * frontWeight,
  };
}

export function withDefaults(settings = {}) {
  return {
    ...DEFAULT_SETTINGS,
    ...settings,
  };
}
